version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: boardgameDB
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"

  mongodb:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"